# -*- coding: utf-8 -*-
"""Final_Year_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oUBzxaGbLa_Mms1lSUaXJNiU57jQZU4T
"""

import numpy as np
import cv2
import pandas as pd
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow
import os
import seaborn as sns
import zipfile
import tensorflow as tf
from tensorflow import keras
from keras.models import load_model
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing import image_dataset_from_directory
from tensorflow.keras.layers import Conv2D,MaxPooling2D,Flatten,Dense,Dropout,InputLayer
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, precision_score, recall_score, f1_score

zip_file_path = '/content/drive/MyDrive/dataset_merged.zip'

if zipfile.is_zipfile(zip_file_path):
    with zipfile.ZipFile(zip_file_path, 'r') as files:
        files.extractall("dataset5")
else:
    print("The file is not a valid zip file.")

from google.colab import drive
drive.mount('/content/drive')

img=cv2.imread("/content/dataset5/dataset_merged/test/Hemorrhagic/11_0_108.jpg")
resize=cv2.resize(img,(256,256))
color=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
fig,ax=plt.subplots(2)
normalize=cv2.normalize(color,None,alpha=0,beta=255,norm_type=cv2.NORM_MINMAX)
ax[0].imshow(img)
ax[0].axis("off")
ax[1].imshow(normalize)
plt.axis("off")

data_dir = r'/content/dataset5/dataset_merged'
train_dir = os.path.join(data_dir, 'train')
test_dir = os.path.join(data_dir,"test")
validation_dir = os.path.join(data_dir,"val")

img_width, img_height = 256, 256

train_datagen = ImageDataGenerator(rescale=1.0/255.0,rotation_range=20)
test_datagen = ImageDataGenerator(rescale=1.0/255.0)
val_datagen=ImageDataGenerator(rescale=1.0/255.0)
train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(img_width, img_height),
    batch_size=32,
     class_mode="sparse",
    color_mode="grayscale"
)

print(train_generator.class_indices)
validation_generator = val_datagen.flow_from_directory(
    validation_dir,
    target_size=(img_width, img_height),
    batch_size=32,
    class_mode="sparse",
    color_mode="grayscale"
)



test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=(img_width, img_height),
    batch_size=32,
    class_mode='sparse',
    shuffle=False,
    color_mode="grayscale"
)

model=Sequential([
    Conv2D(64, (3, 3), activation="relu",input_shape=(256,256,1)),
    Conv2D(64, (3, 3), activation="relu"),
    MaxPooling2D(pool_size=(2, 2)),
    Conv2D(64, (3, 3), activation="relu"),
    MaxPooling2D(pool_size=(2, 2)),
    Conv2D(128, (3, 3), activation="relu"),
    Dropout(0.2),
    Flatten(),
    Dense(3, activation="softmax")
])
model.summary()

model.compile("adam",loss="sparse_categorical_crossentropy",metrics=['accuracy'])


history=model.fit(train_generator,epochs=40,batch_size=32,validation_data=validation_generator)

loss, accuracy = model.evaluate(test_generator)
print('Test Loss:', loss)
print('Test Accuracy:', accuracy)

print(history.history.keys())
plt.plot(history.history["accuracy"])
plt.plot(history.history["val_accuracy"])
plt.xlabel("epoch")
plt.plot("accurcay")
plt.legend(["accuracy","val_accuracy"],loc="lower right")
plt.show()


plt.plot(history.history["loss"])
plt.plot(history.history["val_loss"])
plt.xlabel("epoch")
plt.plot("loss")
plt.legend(["loss","val_loss"],loc="upper right")
plt.show()
class_indices = test_generator.class_indices

y_true=model.predict(test_generator)
print(y_true.shape)
result=np.argmax(y_true,axis=1)
y_test=test_generator.classes
print(y_test)
print(result)
print(classification_report(y_test,result,target_names=test_generator.class_indices.keys()))


y_pred=model.predict(test_generator)
result=np.argmax(y_pred,axis=1)
y_true=test_generator.classes
confusion=confusion_matrix(y_true,result)
print(confusion)


class_names = ["Hemorrhagic","Ischmeic","Normal"]
plt.figure(figsize=(8, 6))
sns.heatmap(confusion, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted labels')
plt.ylabel('True labels')
plt.title('Confusion Matrix')
plt.show()
print(result)
print(y_true)
model.save("latest_model.h5")